version: '3.0'

services:

  mysql:
    image: mysql:5.7-debian
    volumes:
      - /home/grads/financialportfolio-jpa/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: c0nygre
      MYSQL_DATABASE : InvestorsDB
    networks:
      - mysqlnet

  javaapp:
    image: financialportfolio:0.0.1
    environment:
      DB_HOST: mysql
    ports:
      - 8081:8080
    networks:
      - mysqlnet

networks:
  mysqlnet: